# Site settings
description: Learning from the source
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.source.institute" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Salim Virani
user_description: 
user_title: 
email: salim@source.institute
twitter_username: saintsal
github_username:  saintsal
disqus_username: saintsal

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
